{{- if and .Values.chrome.enabled .Values.chrome.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chrome.fullname" . }}
  labels:
    {{- include "chrome.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "chrome.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow incoming traffic only from xwiki pods
    - from:
        - podSelector:
            matchLabels:
              {{- include "xwiki.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.chrome.service.port }}
    {{- with .Values.chrome.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow egress to XWiki pods so Chrome can fetch pages for PDF rendering
    - to:
        - podSelector:
            matchLabels:
              {{- include "xwiki.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.internalPort }}
    {{- with .Values.chrome.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
