{{- if .Values.chrome.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chrome.fullname" . }}
  labels:
    {{- include "chrome.labels" . | nindent 4 }}
  {{- if .Values.chrome.service.annotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
{{ toYaml .Values.commonAnnotations | indent 4 }}
    {{- end }}
    {{- toYaml .Values.chrome.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.chrome.service.type }}
  {{- if .Values.chrome.nginx.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.chrome.service.sessionAffinityTimeoutSeconds }}
  {{- end }}
  ports:
    - port: {{ .Values.chrome.service.port }}
      targetPort: {{ .Values.chrome.service.port }}
      protocol: TCP
      name: {{ .Values.chrome.service.portName }}
  selector:
    {{- include "chrome.selectorLabels" . | nindent 4 }}
{{- end }}
