{{- if and .Values.chrome.enabled .Values.chrome.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chrome.fullname" . }}
  labels:
    {{- include "chrome.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chrome.fullname" . }}
  minReplicas: {{ .Values.chrome.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.chrome.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.chrome.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.chrome.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
