{{- if and .Values.chrome.enabled .Values.chrome.ingress.enabled -}}
{{- $fullName := include "chrome.fullname" . -}}
{{- $svcPort := .Values.chrome.service.port -}}
{{- if and .Values.chrome.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.chrome.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.chrome.ingress.annotations "kubernetes.io/ingress.class" .Values.chrome.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chrome.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.chrome.ingress.annotations }}
{{ toYaml .Values.chrome.ingress.annotations | indent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
{{ toYaml .Values.commonAnnotations | indent 4 }}
    {{- end }}
spec:
  {{- if and .Values.chrome.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.chrome.ingress.className }}
  {{- end }}
  {{- if .Values.chrome.ingress.tls }}
  tls:
    {{- range .Values.chrome.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.chrome.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
            - path: {{ .path }}
              {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
              pathType: {{ .pathType }}
              {{- end }}
              backend:
                {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
                service:
                  name: {{ $fullName }}
                  port:
                    number: {{ $svcPort }}
                {{- else }}
                serviceName: {{ $fullName }}
                servicePort: {{ $svcPort }}
                {{- end }}
          {{- end }}
    {{- end }}
{{- end -}}
