{{- if .Values.chrome.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chrome.fullname" . }}
  labels:
    {{- include "xwiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: chrome
spec:
  {{- if not .Values.chrome.autoscaling.enabled }}
  replicas: {{ .Values.chrome.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "xwiki.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: chrome
  template:
    metadata:
      labels:
        {{- include "xwiki.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: chrome
      {{- if .Values.chrome.podAnnotations }}
      annotations:
        {{- toYaml .Values.chrome.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.chrome.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.chrome.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: remote-chrome
          image: {{ include "chrome.imageName" . }}
          imagePullPolicy: {{ .Values.chrome.image.pullPolicy }}
          args:
            {{- toYaml .Values.chrome.args | nindent 12 }}
            - --remote-debugging-port={{ .Values.chrome.service.port }}
          ports:
            - name: {{ .Values.chrome.service.portName }}
              containerPort: {{ .Values.chrome.service.port }}
              protocol: TCP
          volumeMounts:
            - name: tmp-dir
              mountPath: /tmp
            - name: dshm
              mountPath: /dev/shm
          {{- if .Values.chrome.extraEnvVars }}
          env:
            {{- toYaml .Values.chrome.extraEnvVars | nindent 12 }}
          {{- end }}
          {{- if .Values.chrome.containerSecurityContext.enabled }}
          securityContext:
            {{- omit .Values.chrome.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.chrome.resources }}
          resources:
            {{- toYaml .Values.chrome.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.chrome.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chrome.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chrome.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp-dir
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
{{- end }}
