{{- if .Values.podDisruptionBudget.enabled }}
{{- $fullName := include "xwiki.fullname" . -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "xwiki.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ .Values.commonAnnotations | toYaml | indent 4 }}
    {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "xwiki.selectorLabels" . | nindent 4 }}
{{- end }}